language: python
addons:
 apt:
   packages:
   - gcc
   - libcrack2-dev
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=flake8
  - TOXENV=py27
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py35
  - TOXENV=py35-dj18
  - TOXENV=py35-dj19
