language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install libcrack2-dev
install:
  - pip install tox --use-mirrors
script:
  - tox
env:
  - TOXENV=flake8
  - TOXENV=py27
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py35
  - TOXENV=py35-dj18
  - TOXENV=py35-dj19
