version: "3.7"
services:
  patchman:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/bash", "/patchman-start.sh"]
    environment:
      SECRET_KEY: 'PLEASE_CHANGE_ME_TO_UNIQUE_SECURE_SECRET_KEY'
    ports:
      - '80:80'
    volumes:
      - ./files/patchman-start.sh:/patchman-start.sh
      - ./files/local_settings.py:/etc/patchman/local_settings.py
      - ./files/patchman.conf:/etc/apache2/conf-available/patchman.conf

  database:
    image: mysql:5.7
    restart: always
    command: --init-file /init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'PLEASE_CHANGE_ME_TO_UNIQUE_SECURE_PASSWORD'
    volumes:
      - ./files/init.sql:/init.sql
      - my-db:/var/lib/mysql

volumes:
  my-db:
