---
- name: Patchman Client
  hosts: all
  gather_facts: no 
  become: no
  vars:
    command: patchman-client

  tasks:
  - name: Send report to the Patchman server
    ansible.builtin.shell: |
      if ! command -v {{ command }} &> /dev/null; then 
        >&2 echo "{{ command }}: command not found"; 
        exit 1;
      else 
        sudo {{ command }}; 
      fi
    args:
      executable: /bin/bash
    register: output
